# Generated by Django 3.0.7 on 2021-02-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210211_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firts_name',
            new_name='firt_name',
        ),
    ]
