# Generated by Django 3.0.7 on 2021-02-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210211_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
